"""client, analyst, and page tables

Revision ID: ee209c7f23c7
Revises: ef66ba23137d
Create Date: 2020-03-28 02:19:16.864564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee209c7f23c7'
down_revision = 'ef66ba23137d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_name'), 'analyst', ['name'], unique=True)
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=True)
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html', sa.String(length=16), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('html')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_analyst_name'), table_name='analyst')
    op.drop_table('analyst')
    # ### end Alembic commands ###
